server:
  port: 8701

spring:
  application:
        name: ms-discovery-server

eureka:
    client:
      registerWithEureka: false
      serviceUrl:
        defaultZone: http://192.168.31.149:8701/eureka/
